### ISSUE TITLE
support

### ISSUE THREAD

**Issue by ianhobbs** [whackashoe/antimoderate#10]
Hi Looks fabulous.

Tell me how or what is the long string of characters at the end of the idata attribute ?
Do we just copy that?

**Comment by whackashoe** [comment]
Thanks! 

That is base64 image data for the shrunk images. The ones in the example are just the tiny included images. What you do is at some point during compilation you shrink and encode your images and print them directly into the idata data attribute. 

If you are doing it just for a few pages you can get away with doing it manually. Just shrink the images as small as you want (might be good to test a few sizes), then use either a program on your computer or something [like this](https://www.base64-image.de/) and throw that image data into idata. 

This library only handles the rendering of those shrunk images, not the shrinking and encoding.
