### ISSUE TITLE
support (plugin)

### ISSUE THREAD

**Issue by alejokum122** [whackashoe/antimoderate#11]
Hi.

the plugin looks impressive, but I would like to see a more concrete example on the operation. 
I don't understand how to use this plugin. When the base64 image is shown and when is hidden? whom control this status? me or this plugin does that?

**Comment by whackashoe** [comment]
The base64 image is shown until the full sized image is loaded, then they are swapped. Future reloads of the page you wont see the base64 (unless cache is disabled).

**Comment by alejokum122** [comment]
is necessary use the base64 image?

**Comment by whackashoe** [comment]
It's necessary for antimoderate to work, yeah. Otherwise you wont get the blurry image.

**Comment by sunstorymvp** [comment]
actually not. it works well with just paths to images

**Comment by whackashoe** [comment]
@sunstorymvp I don't follow. What do you mean?

**Comment by sunstorymvp** [comment]
I mean that this is enough:

``` html
<img src="/images/image.jpg" data-antimoderate-idata='/images/image_small.jpg'  style="..."  />
```

It is optional to encode small image to base64, because `idata` argument just passed to `src`:
https://github.com/whackashoe/antimoderate/blob/master/antimoderate.js#L248

it can be any valid `src`

**Comment by whackashoe** [comment]
Aha, you are right! :+1: Thanks
