### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by danielbayerlein** [whackashoe/antimoderate#3]
Which browsers are supported?

**Comment by whackashoe** [comment]
Latest firefox and chrome are really only ones I've tested on. I'm under assumption any browser that implements es5 should work :smile: Would be super happy to have support for older browsers as well. Even with no javascript it will still work so unless the js breaks in between swapping it should gracefully degrade.

**Comment by insign** [comment]
Close this issue, then add this information in the readme.md

**Comment by danielbayerlein** [comment]
Thanks!
