### ISSUE TITLE
better readme / usage guide

### ISSUE THREAD

**Issue by propertunist** [whackashoe/antimoderate#5]
thanks for this idea. what is the best way to populate the data variables for each image in PHP? the readme has no explanation of this aspect of this project and so updating the readme to include full instructions would be a great help.

**Comment by nikolay-mihaylov** [comment]
Guess you have 2 options:
1) if you are storing images on the file system, you read the image and base64_encode it;
2) If you are storing images base64 encoded in your database you just print it in the data attr.

**Comment by whackashoe** [comment]
Right now there is no tool that will automatically do the resizing + base64 of images for you, so you are expected to find a way to do it yourself that suits your usecase. I imagine in future modules in different languages could make this pretty seamless, but for time being those don't exist. 

For php you could create a folder for these base64 images, then write a script with imagemagick to generate the shrunken base64 of all images, then include them ie:

`<img src="whatever.png" data-antimoderate-idata="<?=include('somebase64dir/whatever.png')?>">`

something along those lines

I agree the readme should cover this aspect. Thanks.

**Comment by propertunist** [comment]
i see ok. my site has standard images in a file structure, with no pre-existing dbase / 64bit versions - so i would need to manually encode them using imagemagick, as suggested. that's a bit too much for me to do presently, but i'll make a note and also pass this on to the open source coders who help me with my site - maybe they will consider making a plugin for the elgg framework i am using (www.elgg.org).
